# KORELASYON NEDİR ?

Korelasyon analizi; değişkenler arasındaki ilişki, bu ilişkinin yönü ve şiddeti ile ilgili bilgiler sağlayan istatiksel bir yöntemdir.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("GBvideos.csv")

In [3]:
df

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,Jw1Y-zhQURU,17.14.11,John Lewis Christmas Ad 2017 - #MozTheMonster,John Lewis,26,2017-11-10T07:38:29.000Z,"christmas|""john lewis christmas""|""john lewis""|...",7224515,55681,10247,9479,https://i.ytimg.com/vi/Jw1Y-zhQURU/default.jpg,False,False,False,Click here to continue the story and make your...
1,3s1rvMFUweQ,17.14.11,Taylor Swift: …Ready for It? (Live) - SNL,Saturday Night Live,24,2017-11-12T06:24:44.000Z,"SNL|""Saturday Night Live""|""SNL Season 43""|""Epi...",1053632,25561,2294,2757,https://i.ytimg.com/vi/3s1rvMFUweQ/default.jpg,False,False,False,Musical guest Taylor Swift performs …Ready for...
2,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787420,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
3,PUTEiSjKwJU,17.14.11,Goals from Salford City vs Class of 92 and Fri...,Salford City Football Club,17,2017-11-13T02:30:38.000Z,"Salford City FC|""Salford City""|""Salford""|""Clas...",27833,193,12,37,https://i.ytimg.com/vi/PUTEiSjKwJU/default.jpg,False,False,False,Salford drew 4-4 against the Class of 92 and F...
4,rHwDegptbI4,17.14.11,Dashcam captures truck's near miss with child ...,Cute Girl Videos,25,2017-11-13T01:45:13.000Z,[none],9815,30,2,30,https://i.ytimg.com/vi/rHwDegptbI4/default.jpg,False,False,False,Dashcam captures truck's near miss with child ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,l884wKofd54,18.14.06,Enrique Iglesias - MOVE TO MIAMI (Official Vid...,EnriqueIglesiasVEVO,10,2018-05-09T07:00:01.000Z,"Enrique Iglesias feat. Pitbull|""MOVE TO MIAMI""...",25066952,268088,12783,9933,https://i.ytimg.com/vi/l884wKofd54/default.jpg,False,False,False,NEW SONG - MOVE TO MIAMI feat. Pitbull (Click ...
38912,IP8k2xkhOdI,18.14.06,Jacob Sartorius - Up With It (Official Music V...,Jacob Sartorius,10,2018-05-11T17:09:16.000Z,"jacob sartorius|""jacob""|""up with it""|""jacob sa...",1492219,61998,13781,24330,https://i.ytimg.com/vi/IP8k2xkhOdI/default.jpg,False,False,False,THE OFFICIAL UP WITH IT MUSIC VIDEO!Get my new...
38913,Il-an3K9pjg,18.14.06,Anne-Marie - 2002 [Official Video],Anne-Marie,10,2018-05-08T11:05:08.000Z,"anne|""marie""|""anne-marie""|""2002""|""two thousand...",29641412,394830,8892,19988,https://i.ytimg.com/vi/Il-an3K9pjg/default.jpg,False,False,False,Get 2002 by Anne-Marie HERE ▶ http://ad.gt/200...
38914,-DRsfNObKIQ,18.14.06,Eleni Foureira - Fuego - Cyprus - LIVE - First...,Eurovision Song Contest,24,2018-05-08T20:32:32.000Z,"Eurovision Song Contest|""2018""|""Lisbon""|""Cypru...",14317515,151870,45875,26766,https://i.ytimg.com/vi/-DRsfNObKIQ/default.jpg,False,False,False,Eleni Foureira represented Cyprus at the first...
38915,4YFo4bdMO8Q,18.14.06,KYLE - Ikuyo feat. 2 Chainz & Sophia Black [A...,SuperDuperKyle,10,2018-05-11T04:06:35.000Z,"Kyle|""SuperDuperKyle""|""Ikuyo""|""2 Chainz""|""Soph...",607552,18271,274,1423,https://i.ytimg.com/vi/4YFo4bdMO8Q/default.jpg,False,False,False,Debut album 'Light of Mine' out now: http://ky...

In [4]:
# yukardaki tabloda videoların beğeni sayısı ile görüntülenme sayısı arasında ne kadar kuvvetli ilişki 
# olduğuna bakalım ve bu ilişkinin yönünü bulalım ... (corr komutu ile bakıyoruz ...)

df[["views","likes"]].corr()

          views     likes
views  1.000000  0.795862
likes  0.795862  1.000000

Görüntülenme ve beğeni arasındaki ilişki yaklaşık olarak 0.79 hesaplanmıştır.Pozitif yönlü (görüntülenme arttıkça beğeni artar)
iyi bir ilişki olduğu söylenebilir.

! Korelasyon katsayısı -1 ile +1 arasında değerler alır. Mutlak değer ne kadar büyükse ilişki o kadar kuvvetlidir...

In [5]:
# şimdide beğeni , beğenmeme(dislike) , yorum sayısı ve görüntülenme sayıları arasındaki bu 4 sütunun korelasyonuna 
# birden bakalım ...

df[["views","likes","dislikes","comment_count"]].corr()

                  views     likes  dislikes  comment_count
views          1.000000  0.795862  0.392407       0.466899
likes          0.795862  1.000000  0.446746       0.744361
dislikes       0.392407  0.446746  1.000000       0.771772
comment_count  0.466899  0.744361  0.771772       1.000000

Tabloya bakıldığı zaman görüntülenme ve beğenmeme(dislike) korelasyon katsayısı yaklaşık olarak 0.39 , beğenme ve beğenmeme
arasındaki korelasyon katsayısı yaklaşık olarak 0.44 olarak hesaplanmıştır. Bu ikililer arasında orta düzey pozitif yönlü bir 
ilişki olduğu söylenebilir...

Yine tabloya baktığımız zaman beğenmeme ve yorum sayısı arasındaki korelasyon katsayısı yaklaşık olarak 0.77 , beğenme ve yorum 
sayısı arasındaki korelaasyon katsayısı yaklaşık olara 0.74 hesaplanmıştır. Bu ikililer arasında iyi düzeyde pozitif yönlü bir ilişki olduğu yorumu yapılabilir ...